# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='000', max_length=255),
        ),
    ]
