# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
