var number1 = 3;
console.log("the first number:",number1);
var number2 = 4.5;
console.log("the second number:",number2);
var number3 = 6.78;
console.log("the third number:",number3);
var number4 = 9;
console.log("the fourth number:",number4);
var string1 = "h";
console.log("the first string:"+string1);
var string2 = "el";
console.log("the second string:"+string2);
var string3 = "lo";
console.log("the third string:"+string3);
var t = True;
console.log("the first boolean:",t);
var f = False;
console.log("the second boolean:",f);
var d;
console.log("the undefined variable:",d);